### PR TITLE
fix(classfile): convert `ExceptionTableEntry` byte offsets to instruction offsets

### PR DESCRIPTION
**Pull request by Sculas**
I was using `ristretto_classfile` for a project (thank you so much for making it!). and was surprised by my tests failing when working with the offsets from `ExceptionTableEntry` until I found out they're not converted to instruction offsets for some reason, since only the `handler_pc` is properly converted, but the `range_pc` is not.

This PR fixes that. I've made sure all the tests are passing as well. I had to modify the `test_code` test since the end offset is exclusive.

Also, about the project I was talking about earlier, I'm currently working on a `ristretto_classfile` extension that implements the full `StackMapTable` control flow analysis algorithm. This allows someone (for the first time in Rust!) to modify Java bytecode without having to compute a `StackMapTable` by hand, just like how the ASM library does it in Java. But this can also help with implementing class verification in Ristretto! I'll be publishing it soon (I'm almost done with it), and then I'd like to look into merging it into `ristretto_classfile` so that it can be used in Ristretto as well for class verification.

### CODE REVIEW

**Comment by Sculas** [comment]
What a coincidence haha. Wow. I made this change an hour ago and just PR'd it, and guess what: #172

**Comment by brianheineman** [comment]
Hello @Sculas, thank you for the PR and interest in the project!  I am working my way through trying to get a few things operational on the VM side and noticed that exception handling was not working correctly (fixed in #172).  I'm glad to hear you found the project useful and look forward to seeing the extensions you are proposing!  I'll take a look at this PR in more detail to compare the implementation.  The logic that translates between bytes<->instructions is not currently structured as well as I would like it to be, so there is definitely room for improvement in this area.

**Comment by brianheineman** [comment]
@Sculas I going to close this PR as #172 should address the issue.  In #172, I attempted to retain the semantics defined in [4.7.3](https://docs.oracle.com/javase/specs/jvms/se23/html/jvms-4.html#jvms-4.7.3):

> The start_pc is inclusive and end_pc is exclusive; that is, the exception handler must be active while the program counter is within the interval [start_pc, end_pc).

However, this is a case where the JVM specification has some inconsistencies:

> The fact that end_pc is exclusive is a historical mistake in the design of the Java Virtual Machine: if the Java Virtual Machine code for a method is exactly 65535 bytes long and ends with an instruction that is 1 byte long, then that instruction cannot be protected by an exception handler. A compiler writer can work around this bug by limiting the maximum size of the generated Java Virtual Machine code for any method, instance initialization method, or static initializer (the size of any code array) to 65534 bytes.

I'm inclined to use the specification semantics in this case as it aligns well with the way it is being used in the VM: 

https://doc.rust-lang.org/std/ops/struct.Range.html#method.contains
https://github.com/theseus-rs/ristretto/blob/main/ristretto_vm/src/instruction/exception.rs#L34-L36
```rust
        if !exception_table_entry.range_pc.contains(&program_counter) {
            continue;
        }
```

**Comment by Sculas** [comment]
Yep, I came to the same conclusion as well. Sounds good!

**Comment by brianheineman** [comment]
@Sculas I just released [0.12.1](https://github.com/theseus-rs/ristretto/releases/tag/v0.12.1) which should address this issue.

**Comment by Sculas** [comment]
Thank you so much for the quick fix and release! My tests now pass as well.

**Pull request closed without merging**
